# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestBookingWithCompleteMessage(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testBookingWithCompleteMessage(self):
    self.driver.get("http://localhost:8002/#/")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("xmfnnj@outlook.com")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys("yuechen")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(3) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened .el-menu-item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-col:nth-child(1) .bottom:nth-child(5) span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-col:nth-child(1) .bottom:nth-child(5) span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.XPATH, "//div[3]/div/div/ul/li[3]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(3) .el-select:nth-child(1) .el-input__inner").click()
    self.driver.find_element(By.XPATH, "//div[4]/div/div/ul/li[2]").click()
    self.driver.find_element(By.XPATH, "(//input[@type=\'text\'])[3]").click()
    self.driver.find_element(By.XPATH, "//div[5]/div/div/ul/li[7]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-notification").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-notification").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".el-notification")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".el-notification").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__wrapper:nth-child(4) .el-dialog__close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(2) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(2) .el-menu-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_8 > .cell").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_8 > .cell").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".el-table__row:nth-child(1) > .el-table_2_column_8 > .cell")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".el-button:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary > span").click()
    self.driver.close()
  
