# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test143A(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_143A(self):
    self.driver.get("http://localhost:8002/#/adminLogin")
    self.driver.set_window_size(1200, 783)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("705276106@qq.com")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys("123456")
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(2) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button > .el-icon-edit").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button > .el-icon-edit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").send_keys("测试用的新闻标题")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item__content .el-textarea__inner").send_keys("测试用的新闻内容")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary > span").click()
    
    time.sleep(2)
    assert self.driver.switch_to.alert.text == "发布成功!"
    self.driver.switch_to.alert.accept()
    
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) .el-button--danger").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-table__row:nth-child(1) .el-button--danger")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--default:nth-child(2)").click()
    self.driver.close()
  
