# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test142D(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_142D(self):
    self.driver.get("http://localhost:8002/#/adminLogin")
    self.driver.set_window_size(1440, 826)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("705276106@qq.com")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys("123456")
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(2) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-menu-item:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--medium").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-input__inner").send_keys("新闻标题")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item__content .el-textarea__inner").send_keys("超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字超过两百字")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(2)").click()
    time.sleep(0.5)
    assert self.driver.find_element(By.XPATH, "//*[@id=\"app\"]/div/div/div[2]/div/div[3]/div/div[2]/form/div[2]/div/div[2]").text == "长度在 1 到 200 个字符"
    self.driver.close()
  
