# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestPostCommentWithContent(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testPostCommentWithContent(self):
    self.driver.get("http://localhost:8002/#/")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("xmfnnj@outlook.com")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys("yuechen")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".el-submenu:nth-child(3) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened .el-menu-item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-col:nth-child(1) .bottom:nth-child(4) span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-textarea__inner").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-notification").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-notification").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".el-notification")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(27) .clearfix").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(27) .clearfix").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "div:nth-child(27) .clearfix")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(27) .el-button > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__wrapper:nth-child(3) .el-dialog__close").click()
    self.driver.close()
  
