# Generated by Selenium IDE
import unittest
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdminLoginWithInValidPassword(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminLoginWithInValidPassword(self):
    self.driver.get("http://localhost:8002/#/adminLogin")
    self.driver.set_window_size(1440, 830)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-input__inner").send_keys("852092786@qq.com")
    self.driver.find_element(By.CSS_SELECTOR, ".el-input--suffix > .el-input__inner").send_keys("654321")
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)

    self.driver.find_element(By.CSS_SELECTOR, ".el-message__content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-message__content").click()

    self.driver.close()
  
